### ISSUE TITLE
Will not copy to "Archive File" on Windows 10 system

### ISSUE THREAD

**Issue by marcpare4** [snap-backup/snapbackup#2]
I have the "Copy to" tagged and the file location on an external USB drive properly setup.

Snap Backup does the full .zip backup in the "Backup" folder but does not do the copying of the archive file.

**Comment by dpilafian** [comment]
It sounds like you properly checked the `Copy Backup To:` option.

After you run the backup, the last four lines in the **Message Log** box should look something like:

    Backup File Created: /Users/dem/Heap/Backup/Projects 2016-06-28.zip  [5,387 KB]
    Archived Backup: /Users/dem/Dropbox/Storage/Backup/Projects 2016-06-28.zip
    Memory Used: 9.0%  [167,936 KB]  /  Elapsed Time: 0 min 5.32 sec
    --- End ----

1) What do you see for the `Archived Backup` line?

2) To make sure the archive path is understood by the system, use the button with the folder icon to select the USB drive.

**Comment by dpilafian** [comment]
https://snapbackup.org/screen
