### ISSUE TITLE
Command line example

### ISSUE THREAD

**Issue by RottenRonnie** [snap-backup/snapbackup#9]
I love that I can run snap backup as a scheduled task called from a batch file, but sadly the documentation tends to drop the ball on exactly how this is done. For example, I was expecting to find a config file for "Main" as an xml, cfg, ini or .json.
Is it possibly to view or modify the "main" profile? 

Would you mind adding a working example of the command line method of calling your app to the FAQ section? 

```
REM runs Snap Backup jar file with "main" or "~" profile 
java -jar "C:\Program Files\SnapBackup\app\snapbackup.jar" main
```

Thank you. 
I would also add a donate button. I love this app!

**Comment by dpilafian** [comment]
The Snap Backup website has just been updated to make it more obvious how to navigate to the _User Guide._

Here's the **"Command-Line Option"** section:
https://snapbackup.org/snap-backup-user-guide.html#command-line

There's an example for backing up the a profile named `spreadsheets`:
```terminal
$ java -jar snapbackup.jar spreadsheets 
```

Edits and enhancements to the _User Guide_ are welcome.

The HTML for the _User Guide._ is at:
https://github.com/snap-backup/snapbackup/blob/main/src/resources/snap-backup-user-guide.html

You can either create a pull request with your changes or just post your changes as a comment on this issue.

**Comment by RottenRonnie** [comment]
Note that I had to upgrade to version 6.5.0 before I was able to use the multi profile "--list" feature. 

**Prior to upgrade:**
Snap Backup 6.2.0
--- Start ---
Profile: --list
*** ERROR #30 ~ Profile not found: --list
*** Aborted ***
Memory Used: 6.3%  [260,096 KB]  /  Elapsed Time: 0 min 0.02 sec
--- End ---

**Post upgrade:**
Snap Backup v6.5.0
Backup Profiles: 1
   "Main"
Current: "Main"

![2023-02-23 15_44_52-Command Prompt](https://user-images.githubusercontent.com/10812745/221013748-ffad3d7f-4eb4-46b9-b1b7-b16de00606c0.jpg)

Thank you!
